<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [

 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED  
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
]>
<SystemDefinition name="S60_SystemBuild" schema="1.4.0">
<systemModel>


	<layer name="os_layer">
	</layer>
	<layer name="bldfirst_mw_layer">
	</layer>
	<layer name="mw_layer">
	</layer>
	<layer name="bldfirst_app_layer">
	</layer>
	<layer name="app_layer">
	</layer>
	<layer name="tools_layer">
	</layer>
	<layer name="stubs_layer">
	</layer>

<layer name="src">
<module name="hlpmodel">
<component name="hlpmodel">
<unit unitID="S60_hlpmodel" name="hlpmodel" bldFile="\src\common\generic\app-services\hlpmodel\group" mrp=""/>
</component>
</module>
</layer>
<layer name="extra">
	<module name="WlanEapSettingsUi_ccx">
		<component name="WlanEapSettingsUi_ccx">
			<unit unitID="s60_mw_networking_networkingutilities_WlanEapSettingsUi_group_ccx" name="WlanEapSettingsUi_ccx" bldFile="\sf\mw\accesssec\wlansecuritysettings\wlaneapsettingsui\group\ccx" mrp=""/>
		</component>
	</module>
</layer>

<layer name="SF_SOS">
<module name="sf_licenseetsystub">
<component name="sf_licenseetsystub">
<unit unitID="sf_os_cellularsrv_telephonyserverplugins_licenseetsystub" name="sf_licenseetsystub" bldFile="\sf\os\cellularsrv\telephonyserverplugins\licenseetsystub\group" mrp="" filter="!no_stubs"/>
</component>
</module>
<module name="sf_common_tsy">
<component name="sf_common_tsy">
<unit unitID="sf_os_cellularsrv_telephonyserverplugins_common_tsy" name="sf_common_tsy" bldFile="\sf\os\cellularsrv\telephonyserverplugins\common_tsy\group" mrp="" filter=""/>
</component>
</module>
</layer>

</systemModel>

  <build>
    <option name="KEEPGOING" abldOption="-keepgoing" description="Causes make to keepgoing on errors" enable="Y"/>
<!--    <option name="SAVESPACE" abldOption="-savespace" description="Causes the removal of intermediate files" enable="Y"/> -->
    <target name="WINS" abldTarget="wins" description="MSVC Compiler"/>
    <target name="WINS_REL" abldTarget="wins urel" description="MSVC Compiler"/>
    <target name="WINS_DEB" abldTarget="wins udeb" description="MSVC Compiler"/>
    <target name="WINSCW" abldTarget="winscw" description="CodeWarrior Compiler"/>
    <target name="WINSCW_REL" abldTarget="winscw urel" description="CodeWarrior Compiler"/>
    <target name="WINSCW_DEB" abldTarget="winscw udeb" description="CodeWarrior Compiler"/>
    <target name="TOOLS" abldTarget="tools" description="MSVC Compiler for Tools"/>
    <target name="TOOLS_REL" abldTarget="tools rel" description="MSVC Compiler for Tools Release mode only"/>
    <target name="ARMV5" abldTarget="armv5" description="RVCT Compiler"/>
    <target name="ARMV5_REL" abldTarget="armv5 urel" description="RVCT Compiler"/>
    <target name="ARMV5_DEB" abldTarget="armv5 udeb" description="RVCT Compiler"/>
    <target name="ARM9E" abldTarget="arm9e" description="RVCT Compiler"/>

    <!-- Aditional Targets -->
    <target name="CWTOOLS" abldTarget="cwtools" description="CodeWarrior Compiler for Tools"/> <!-- Not supported -->
    <target name="CWTOOLS_REL" abldTarget="cwtools rel" description="CodeWarrior Compiler for Tools Release mode only"/> <!-- Not supported -->
    
    <targetList name="default" description="Main Targets" target="WINSCW ARMV5"/>
    <targetList name="default_winscw" description="Main Targets" target="WINSCW"/>
    <targetList name="default_armv5" description="Main Targets" target="ARMV5"/>
    <targetList name="default_rel" description="Main Targets for rel" target="WINSCW_REL ARMV5_REL"/>
    <targetList name="default_deb" description="Main Targets for deb" target="WINSCW_DEB ARMV5_DEB"/>
    <targetList name="default_debrel" description="Main Targets for WINSCW deb and ARMV5 urel" target="WINSCW_DEB ARMV5_REL"/>
    <targetList name="default_tools" description="tools Targets" target="TOOLS"/>
    <targetList name="tools_rel" description="tools Release Targets" target="TOOLS_REL"/>
    <targetList name="cwtools" description="cwtools Targets" target="CWTOOLS"/>
    <targetList name="cwtools_rel" description="cwtools Release Targets" target="CWTOOLS_REL"/>
    <targetList name="arm9e" description="arm9e Release Targets" target="ARM9E"/>
  

  
   	<configuration name="S60_bldmelast" description="S60 bldmelast part" filter="S60_5_0,western,raptor_S60_bldmelast">

<!-- for target arm9e 
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="abld build arm9e -k"/></task> 
-->
			<layerRef layerName="arm9e_layer"/>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
  		<task><buildLayer command="abld build " targetList="arm9e" unitParallel="Y" targetParallel="Y"/></task>
  		<task><buildLayer command="abld build -what" targetList="arm9e" unitParallel="Y" targetParallel="Y"/></task>
  		<task><buildLayer command="abld build -check" targetList="arm9e" unitParallel="Y" targetParallel="Y"/></task>

  	</configuration>

   	<configuration name="S60_bldmelast_sf" description="S60 bldmelast part" filter="S60_5_0,western">
      <!--unitListRef unitList="S60_BLDVARIANT_SF"/>   		
   		<unitListRef unitList="S60_REGIONALVARIANT"/-->

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
  		<task><buildLayer command="abld makefile" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  		<task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>

  	</configuration>
  	
		<configuration name="S60_clean" description="S60 clean build" filter="raptor_S60_clean,oem_build,stubs">
			<layerRef layerName="os_layer"/>
			<layerRef layerName="bldfirst_mw_layer"/>
			<layerRef layerName="mw_layer"/>
			<layerRef layerName="bldfirst_app_layer"/>
			<layerRef layerName="app_layer"/>
			<layerRef layerName="tools_layer"/>
			<layerRef layerName="stubs_layer"/>
			      
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>

		<configuration name="S60_sf" description="S60 sf build" filter="raptor_S60_sf,sf_build">
			<layerRef layerName="os_layer"/>
			<layerRef layerName="bldfirst_mw_layer"/>
			<layerRef layerName="mw_layer"/>
			<layerRef layerName="bldfirst_app_layer"/>
			<layerRef layerName="app_layer"/>
			<layerRef layerName="tools_layer"/>
			<layerRef layerName="stubs_layer"/>
			     
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>
    
		<configuration name="S60_winscw" description="S60 winscw build" filter="oem_build">
			<layerRef layerName="os_layer"/>
			<layerRef layerName="bldfirst_mw_layer"/>
			<layerRef layerName="mw_layer"/>
			<layerRef layerName="bldfirst_app_layer"/>
			<layerRef layerName="app_layer"/>
			<layerRef layerName="tools_layer"/>
			<layerRef layerName="stubs_layer"/>

      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>

		<configuration name="S60_fast" description="S60 clean build for winscw udeb and armv5 urel" filter="oem_build">
			<layerRef layerName="os_layer"/>
			<layerRef layerName="bldfirst_mw_layer"/>
			<layerRef layerName="mw_layer"/>
			<layerRef layerName="bldfirst_app_layer"/>
			<layerRef layerName="app_layer"/>
			<layerRef layerName="tools_layer"/>
			<layerRef layerName="stubs_layer"/>
      
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_debrel" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_debrel" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_debrel" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_debrel" unitParallel="Y" targetParallel="Y"/></task>
      
    </configuration>


		<configuration name="S60_complementary" description="S60 complementary build" filter="raptor_S60_complementary">
			<layerRef layerName="complementary_layer"/>
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>

<!--  
launch -what command for binary only component so thosa can be zipped  
this configuration can be used only when those components has built among normal build
-->
		<configuration name="binary_only_what" description="do what command for binary only components" filter="raptor_binary_only_what">
			<layerRef layerName="bin_layer"/>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>


<!--  OS Extension build configurations start  -->

	<configuration name="OSExt" description="S60 OS Extension build" filter="osext,dfs_build">
			<layerRef layerName="os_layer"/>
			<layerRef layerName="stubs_layer"/>
      <task><buildLayer command="bldmake bldfiles -k" unitParallel="Y"/></task>
      <task><buildLayer command="abld export -k" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target -k" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  	  <task><buildLayer command="abld final" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>

  </build>
</SystemDefinition>
